### ISSUE TITLE
Browser command on no GUI server

### ISSUE THREAD

**Issue by dinosauria123** [ongaeshi/honyomi-web#1]
Sorry, I am not familiar to web application. 
It may be stupid question but I can not solve it.

I try to install honyomi-web by following your instructions, and run honyomi web I got such errors.
  .....lib/launchy/applications/browser.rb:63:in `browser_cmdline': Unable to find a browser command. If th
  is is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiou
  sfreetime/launchy/issues/new (Launchy::CommandNotFoundError) 

I think it seems to install web browser such as FireFox, but installed honyomi no GUI system (VM on Google Compute Engine).

I also use headless browser (xvfb) but no success.

If you know any solution please help me.

I used Ubuntu 17.04 on Google Compute Engine.

Regards,

**Comment by dinosauria123** [comment]
I have checked my problem more precisely
I found apache2 error log says "permision denied" in honyomi.db at /var/www/html/honyomi/data/db.
Could you tell me proper setting ? 

[ 2017-08-18 09:59:27.6823 1910/7f01532cc700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a 
spawning error occurred. The identifier of the error is 7909be87. Please see earlier logs for details about the error.
App 2214 stdout: 
App 2214 stdout: 
[ 2017-08-18 10:03:27.6581 1910/7f015152c700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/html/honyomi: An error occurred while starting up the preloader.
  Error ID: b3e66f5a
  Error details saved to: /tmp/passenger-error-SgscVp.html
  Message from application: permission denied: system call error: Permission denied: failed to open path: </var/www/html/honyomi/data/db/honyomi.db>: #<Groonga::Database>
io.c:586: grn_io_open() (Groonga::PermissionDenied)
  /var/www/html/honyomi/app.rb:3:in `open'
  /var/www/html/honyomi/app.rb:3:in `<top (required)>'
  config.ru:1:in `require'
  config.ru:1:in `block in <main>'
  /var/www/html/honyomi/vender/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/html/honyomi/vender/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by dinosauria123** [comment]
I could run honyomi-web by re-install honyomi-web from git server.

I need install other packages,

• apache2
• ruby2.3
• ruby-bundler 
• pdf-popper

In addition, passenger and passenger-install-apache2-module from gem.

Thank you for giving us good software !

**Comment by ongaeshi** [comment]
Thank you for the report.

I did not understand cause of error but it seems that it worked.

There is also a [docker-honyomi](https://github.com/ongaeshi/docker-honyomi) for Docker, so for reference.
