### ISSUE TITLE
Can not delete already added book

### ISSUE THREAD

**Issue by dinosauria123** [ongaeshi/honyomi-web#2]
Sorry, I am back again.

I can not delete already added books from web interface.

I tried to re-init honyomi db, but top page of the honyomi-web still remain books after honyomi init....

**Comment by ongaeshi** [comment]
Sorry, Honyomi cannot remove books from web.

Please use commandline.

```
# List 
$ honyomi list
1 This is Book (10 pages)
2 Want to remove Book (20 pages)
.
.

# Remove 
$ honyomi rm 2
```

**Comment by dinosauria123** [comment]
Thank you for your quick answer.

My temporary honyomi server is here.

http://104.197.98.173

I am a old camera lover and making a database WWII era Japanese camera advertisements.

Honyomi is good tool, I can make easily my own database web server.

Thank you for your efforts.

**Comment by ongaeshi** [comment]
Cool! Thank you for using Honyomi. :smile:
